### ISSUE TITLE
issue when joining server(1.14.4)

### ISSUE THREAD

**Issue by SDUBZ** [Draylar/vanilla-toolsets#12]
[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/WARN]: Failed to handle packet for /124.190.206.65:10021net.minecraft.class_148: Ticking playerat net.minecraft.class_3222.method_14226(class_3222.java:452) ~[intermediary-server.jar:?]at net.minecraft.class_3244.method_18784(class_3244.java:196) ~[intermediary-server.jar:?]at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server.jar:?]at net.minecraft.class_3242.method_14357(class_3242.java:171) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:847) [intermediary-server.jar:?]at net.minecraft.class_3176.method_3813(class_3176.java:343) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:774) [intermediary-server.jar:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [intermediary-server.jar:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.ClassCastException: com.github.draylar.vanilla_toolsets.common.items.materials.ArmorMaterialEmerald incompatible with marioandweegee3.toolbuilder.common.armor.ArmorWeightat net.minecraft.class_1657.handler$setArmorWeightSpeed$zmb000(class_1657.java:6760) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6029(class_1657.java:1568) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_18802(class_1309.java:2025) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6091(class_1309.java:1957) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6091(class_1657.java:1547) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_6007(class_1309.java:2296) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_6007(class_1657.java:560) ~[intermediary-server.jar:?]at net.minecraft.class_1309.method_5773(class_1309.java:2111) ~[intermediary-server.jar:?]at net.minecraft.class_1657.method_5773(class_1657.java:277) ~[intermediary-server.jar:?]at net.minecraft.class_3222.method_14226(class_3222.java:388) ~[intermediary-server.jar:?]... 8 more[08:33:09] [Server thread/INFO]: swh65458 lost connection: Disconnected[08:33:09] [Server thread/INFO]: swh65458 left the game

**Comment by Draylar** [comment]
Fixed with Tool Builder's latest update.
